[package]
name = "opengl-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.4.0"
soup = "0.5.1"
html5ever = "0.22"
itertools = "0.10.3"